### ISSUE TITLE
Awesome Weak Supervision

### ISSUE THREAD

**Issue by yueyu1030** [Nachimak28/awesome-list-of-awesomes#3]
Hi,

Thanks for this awesome repo! Here is a curated list of programmatic/rule-based weak supervision papers and resources: https://github.com/JieyuZ2/Awesome-Weak-Supervision.

It would be great if you can add this to your repo. Many thanks!

Best,
Yue

**Comment by Nachimak28** [comment]
Hi, Thanks for creating the issue, I did search for something like this but couldn't find anything. 
I've added it to the Weakly Supervised learning list.

Closing this issue.
